package CodeGenerationLanguaage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Cardinality extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Cardinality() {
    super(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad15e5bL, "Cardinality", "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393179");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember__1_0 = new EnumerationDescriptor.MemberDescriptor("_1", "1", 0x255c2eaad15e5cL, "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393180");
  private final EnumerationDescriptor.MemberDescriptor myMember__0_1_0 = new EnumerationDescriptor.MemberDescriptor("_0_1", "0..1", 0x255c2eaad15e5dL, "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393181");
  private final EnumerationDescriptor.MemberDescriptor myMember__0_n_0 = new EnumerationDescriptor.MemberDescriptor("_0_n", "0..n", 0x255c2eaad15e60L, "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393184");
  private final EnumerationDescriptor.MemberDescriptor myMember__1_n_0 = new EnumerationDescriptor.MemberDescriptor("_1_n", "1..n", 0x255c2eaad15e64L, "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393188");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad15e5bL, 0x255c2eaad15e5cL, 0x255c2eaad15e5dL, 0x255c2eaad15e60L, 0x255c2eaad15e64L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember__1_0, myMember__0_1_0, myMember__0_n_0, myMember__1_n_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember__1_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "_1":
        return myMember__1_0;
      case "_0_1":
        return myMember__0_1_0;
      case "_0_n":
        return myMember__0_n_0;
      case "_1_n":
        return myMember__1_n_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
