package CodeGenerationLanguaage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RelationshipType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RelationshipType() {
    super(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad15e6aL, "RelationshipType", "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393194");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_association_0 = new EnumerationDescriptor.MemberDescriptor("association", "ref", 0x255c2eaad15e6bL, "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393195");
  private final EnumerationDescriptor.MemberDescriptor myMember_aggregation_0 = new EnumerationDescriptor.MemberDescriptor("aggregation", "aggr", 0x255c2eaad15e6cL, "r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642393196");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad15e6aL, 0x255c2eaad15e6bL, 0x255c2eaad15e6cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_association_0, myMember_aggregation_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_association_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "association":
        return myMember_association_0;
      case "aggregation":
        return myMember_aggregation_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
