package CodeGenerationLanguaage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAttribute = createDescriptorForAttribute();
  /*package*/ final ConceptDescriptor myConceptBoolean = createDescriptorForBoolean();
  /*package*/ final ConceptDescriptor myConceptCollectionType = createDescriptorForCollectionType();
  /*package*/ final ConceptDescriptor myConceptDAO = createDescriptorForDAO();
  /*package*/ final ConceptDescriptor myConceptDAOReference = createDescriptorForDAOReference();
  /*package*/ final ConceptDescriptor myConceptDomainObject = createDescriptorForDomainObject();
  /*package*/ final ConceptDescriptor myConceptDomainObjectComponent = createDescriptorForDomainObjectComponent();
  /*package*/ final ConceptDescriptor myConceptDouble = createDescriptorForDouble();
  /*package*/ final ConceptDescriptor myConceptEntity = createDescriptorForEntity();
  /*package*/ final ConceptDescriptor myConceptFloat = createDescriptorForFloat();
  /*package*/ final ConceptDescriptor myConceptInteger = createDescriptorForInteger();
  /*package*/ final ConceptDescriptor myConceptList = createDescriptorForList();
  /*package*/ final ConceptDescriptor myConceptModule = createDescriptorForModule();
  /*package*/ final ConceptDescriptor myConceptModuleComponent = createDescriptorForModuleComponent();
  /*package*/ final ConceptDescriptor myConceptPrimitiveType = createDescriptorForPrimitiveType();
  /*package*/ final ConceptDescriptor myConceptRelationship = createDescriptorForRelationship();
  /*package*/ final ConceptDescriptor myConceptRepository = createDescriptorForRepository();
  /*package*/ final ConceptDescriptor myConceptService = createDescriptorForService();
  /*package*/ final ConceptDescriptor myConceptSet = createDescriptorForSet();
  /*package*/ final ConceptDescriptor myConceptString = createDescriptorForString();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  /*package*/ final ConceptDescriptor myConceptValueObject = createDescriptorForValueObject();
  /*package*/ final EnumerationDescriptor myEnumerationCardinality = new EnumerationDescriptor_Cardinality();
  /*package*/ final EnumerationDescriptor myEnumerationRelationshipType = new EnumerationDescriptor_RelationshipType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAttribute, myConceptBoolean, myConceptCollectionType, myConceptDAO, myConceptDAOReference, myConceptDomainObject, myConceptDomainObjectComponent, myConceptDouble, myConceptEntity, myConceptFloat, myConceptInteger, myConceptList, myConceptModule, myConceptModuleComponent, myConceptPrimitiveType, myConceptRelationship, myConceptRepository, myConceptService, myConceptSet, myConceptString, myConceptType, myConceptValueObject);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Attribute:
        return myConceptAttribute;
      case LanguageConceptSwitch.Boolean:
        return myConceptBoolean;
      case LanguageConceptSwitch.CollectionType:
        return myConceptCollectionType;
      case LanguageConceptSwitch.DAO:
        return myConceptDAO;
      case LanguageConceptSwitch.DAOReference:
        return myConceptDAOReference;
      case LanguageConceptSwitch.DomainObject:
        return myConceptDomainObject;
      case LanguageConceptSwitch.DomainObjectComponent:
        return myConceptDomainObjectComponent;
      case LanguageConceptSwitch.Double:
        return myConceptDouble;
      case LanguageConceptSwitch.Entity:
        return myConceptEntity;
      case LanguageConceptSwitch.Float:
        return myConceptFloat;
      case LanguageConceptSwitch.Integer:
        return myConceptInteger;
      case LanguageConceptSwitch.List:
        return myConceptList;
      case LanguageConceptSwitch.Module:
        return myConceptModule;
      case LanguageConceptSwitch.ModuleComponent:
        return myConceptModuleComponent;
      case LanguageConceptSwitch.PrimitiveType:
        return myConceptPrimitiveType;
      case LanguageConceptSwitch.Relationship:
        return myConceptRelationship;
      case LanguageConceptSwitch.Repository:
        return myConceptRepository;
      case LanguageConceptSwitch.Service:
        return myConceptService;
      case LanguageConceptSwitch.Set:
        return myConceptSet;
      case LanguageConceptSwitch.String:
        return myConceptString;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      case LanguageConceptSwitch.ValueObject:
        return myConceptValueObject;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationCardinality, myEnumerationRelationshipType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Attribute", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b8L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.DomainObjectComponent
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad371a8L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929629906104");
    b.version(3);
    b.property("businessKey", 0x255c2eaa12d4b9L).type(PrimitiveTypeId.BOOLEAN).origin("10515929629906105").done();
    b.property("primaryKey", 0x255c2eac2cc5fcL).type(PrimitiveTypeId.BOOLEAN).origin("10515929665160700").done();
    b.aggregate("type", 0x255c2eaa12d4bbL).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b3L).optional(false).ordered(true).multiple(false).origin("10515929629906107").done();
    b.alias("property");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Boolean", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edcbbL);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.PrimitiveType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b0L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929633840315");
    b.version(3);
    b.alias("bool");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCollectionType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "CollectionType", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa84L);
    b.class_(false, true, false);
    // extends: CodeGenerationLanguaage.structure.Type
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b3L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929631488644");
    b.version(3);
    b.aggregate("elementType", 0x255c2eaa2afa85L).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b3L).optional(false).ordered(true).multiple(false).origin("10515929631488645").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDAO() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "DAO", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4b33L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.ModuleComponent
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4adfL);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929663228723");
    b.version(3);
    b.associate("domainObject", 0x255c2eac906680L).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4a8L).optional(false).origin("10515929671689856").done();
    b.alias("dao");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDAOReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "DAOReference", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac1cf42dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929664123949");
    b.version(3);
    b.associate("target", 0x255c2eac1cf42eL).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4b33L).optional(false).origin("10515929664123950").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "DomainObject", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4a8L);
    b.class_(false, true, true);
    // extends: CodeGenerationLanguaage.structure.ModuleComponent
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4adfL);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929629906088");
    b.version(3);
    b.aggregate("components", 0x255c2eaa12d4bdL).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad371a8L).optional(true).ordered(true).multiple(true).origin("10515929629906109").done();
    b.alias("domainObject");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainObjectComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "DomainObjectComponent", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad371a8L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642529192");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDouble() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Double", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edc6eL);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.PrimitiveType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b0L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929633840238");
    b.version(3);
    b.alias("double");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Entity", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa117514L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.DomainObject
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4a8L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929629816084");
    b.version(3);
    b.property("aggregateRoot", 0x255c2eaa12d4adL).type(PrimitiveTypeId.BOOLEAN).origin("10515929629906093").done();
    b.alias("entity");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFloat() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Float", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edc23L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.PrimitiveType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b0L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929633840163");
    b.version(3);
    b.alias("float");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Integer", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4afL);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.PrimitiveType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b0L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929629906095");
    b.version(3);
    b.alias("int");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "List", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa83L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.CollectionType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa84L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929631488643");
    b.version(3);
    b.alias("list");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Module", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eab8a8900L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929654528256");
    b.version(3);
    b.aggregate("components", 0x255c2eab8a8901L).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4adfL).optional(true).ordered(true).multiple(true).origin("10515929654528257").done();
    b.alias("module");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModuleComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "ModuleComponent", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4adfL);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929663228639");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPrimitiveType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "PrimitiveType", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b0L);
    b.class_(false, true, false);
    // extends: CodeGenerationLanguaage.structure.Type
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b3L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929629906096");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRelationship() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Relationship", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad11a37L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.DomainObjectComponent
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad371a8L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929642375735");
    b.version(3);
    b.property("cardinality", 0x255c2eaad15e6fL).type(MetaIdFactory.dataTypeId(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad15e5bL)).origin("10515929642393199").done();
    b.property("type", 0x255c2eaad15e71L).type(MetaIdFactory.dataTypeId(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaad15e6aL)).origin("10515929642393201").done();
    b.associate("target", 0x255c2eaad11a3bL).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4a8L).optional(false).origin("10515929642375739").done();
    b.alias("rel");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRepository() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Repository", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eabff1816L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.ModuleComponent
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4adfL);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929662167062");
    b.version(3);
    b.aggregate("daos", 0x255c2eac1cf430L).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac1cf42dL).optional(true).ordered(true).multiple(true).origin("10515929664123952").done();
    b.alias("repository");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForService() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Service", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4ae2L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.ModuleComponent
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4adfL);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929663228642");
    b.version(3);
    b.aggregate("repositories", 0x255c2eac0f4ae3L).target(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eabff1816L).optional(true).ordered(true).multiple(true).origin("10515929663228643").done();
    b.alias("service");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Set", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa5f9e38L);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.CollectionType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa84L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929634938424");
    b.version(3);
    b.alias("set");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "String", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa28855bL);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.PrimitiveType
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b0L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929631327579");
    b.version(3);
    b.alias("string");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "Type", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b3L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929629906099");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValueObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeGenerationLanguaage", "ValueObject", 0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eabfa8cbcL);
    b.class_(false, false, false);
    // extends: CodeGenerationLanguaage.structure.DomainObject
    b.super_(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4a8L);
    b.origin("r:c6f8b706-f070-414f-9c0e-2eb2b52aae6c(CodeGenerationLanguaage.structure)/10515929661869244");
    b.version(3);
    b.alias("valueObject");
    return b.create();
  }
}
