package CodeGenerationLanguaage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class CollectionType_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SNodeOperations.isInstanceOf(ctx.getPrimaryInput(), CONCEPTS.List$KA)) {
      tgs.append("List");
    } else if (SNodeOperations.isInstanceOf(ctx.getPrimaryInput(), CONCEPTS.Set$Zc)) {
      tgs.append("Set");
    }
    tgs.append("<");
    if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.elementType$cMik), CONCEPTS.Integer$4L)) {
      tgs.append(Integer.class.getSimpleName());
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.elementType$cMik), CONCEPTS.Float$ob)) {
      tgs.append(Float.class.getSimpleName());
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.elementType$cMik), CONCEPTS.Double$Z2)) {
      tgs.append(Double.class.getSimpleName());
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.elementType$cMik), CONCEPTS.String$P8)) {
      tgs.append(String.class.getSimpleName());
    } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.elementType$cMik), CONCEPTS.Boolean$L2)) {
      tgs.append(Boolean.class.getSimpleName());
    }
    tgs.append(">");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept List$KA = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa83L, "CodeGenerationLanguaage.structure.List");
    /*package*/ static final SConcept Set$Zc = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa5f9e38L, "CodeGenerationLanguaage.structure.Set");
    /*package*/ static final SConcept Integer$4L = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4afL, "CodeGenerationLanguaage.structure.Integer");
    /*package*/ static final SConcept Float$ob = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edc23L, "CodeGenerationLanguaage.structure.Float");
    /*package*/ static final SConcept Double$Z2 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edc6eL, "CodeGenerationLanguaage.structure.Double");
    /*package*/ static final SConcept String$P8 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa28855bL, "CodeGenerationLanguaage.structure.String");
    /*package*/ static final SConcept Boolean$L2 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edcbbL, "CodeGenerationLanguaage.structure.Boolean");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink elementType$cMik = MetaAdapterFactory.getContainmentLink(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa84L, 0x255c2eaa2afa85L, "elementType");
  }
}
