package CodeGenerationLanguaage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import CodeGenerationLanguaage.behavior.DomainObject__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import CodeGenerationLanguaage.behavior.DomainObjectComponent__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class DAO_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("package ");
    tgs.append(SPropertyOperations.getString(SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.Module$FI, false, false), PROPS.name$MnvL));
    tgs.append(".persistence;");
    tgs.newLine();
    tgs.newLine();

    tgs.append("import ");
    tgs.append(SPropertyOperations.getString(SNodeOperations.getNodeAncestor(ctx.getPrimaryInput(), CONCEPTS.Module$FI, false, false), PROPS.name$MnvL));
    tgs.append(".model.");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.newLine();
    tgs.newLine();


    tgs.append("public interface ");
    tgs.append("I");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append(" extends DAO<");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(", ");
    tgs.appendNode(DomainObject__BehaviorDescriptor.getPrimaryKeyType_id_n2UGq_9d.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi)));
    tgs.append("> {");
    tgs.newLine();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

    tgs.append("public enum ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append(" implements I");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append(" {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("INSTANCE;");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("private ServicioPersistencia servPersistencia;");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("private ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append("() {");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("this.servPersistencia = FactoriaServicioPersistencia.getInstance().getServicioPersistencia();");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

    tgs.indent();
    tgs.append("@Override");
    tgs.newLine();
    tgs.indent();
    tgs.append("public void insert(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(") {");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("Entidad e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" = ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append("ToEntidad(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(");");
    tgs.newLine();
    tgs.indent();
    tgs.append("e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" = servPersistencia.registrarEntidad(e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(");");
    tgs.newLine();
    tgs.indent();
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(".setId(e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(".getId());");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();


    tgs.indent();
    tgs.append("@Override");
    tgs.newLine();
    tgs.indent();
    tgs.append("public void delete(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(") {");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("Entidad e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" = servPersistencia.recuperarEntidad(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(".getId());");
    tgs.newLine();
    tgs.indent();
    tgs.append("servPersistencia.borrarEntidad(e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(");");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();


    tgs.indent();
    tgs.append("@Override");
    tgs.newLine();
    tgs.indent();
    tgs.append("public void update(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(") {");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("Entidad e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" = servPersistencia.recuperarEntidad(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
    tgs.append(".getId());");
    tgs.newLine();

    for (SNode elem : SetSequence.fromSet(DomainObject__BehaviorDescriptor.getAttributes_id_n2UGGOIx.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi)))) {
      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(elem, LINKS.type$3xxQ), CONCEPTS.Integer$4L) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(elem, LINKS.type$3xxQ), CONCEPTS.Double$Z2) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(elem, LINKS.type$3xxQ), CONCEPTS.Float$ob) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(elem, LINKS.type$3xxQ), CONCEPTS.Boolean$L2)) {
        tgs.indent();
        tgs.append("servPersistencia.eliminarPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\");");
        tgs.newLine();
        tgs.indent();
        tgs.append("servPersistencia.anadirPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\", String.valueOf(");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
        tgs.append(".get");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(1));
        tgs.append("()));");
        tgs.newLine();
      } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(elem, LINKS.type$3xxQ), CONCEPTS.String$P8)) {
        tgs.indent();
        tgs.append("servPersistencia.eliminarPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\");");
        tgs.newLine();
        tgs.indent();
        tgs.append("servPersistencia.anadirPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\", ");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
        tgs.append(".get");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(1));
        tgs.append("());");
        tgs.newLine();
      } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(elem, LINKS.type$3xxQ), CONCEPTS.CollectionType$L5)) {
        tgs.indent();
        tgs.append("servPersistencia.eliminarPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\");");
        tgs.newLine();
        tgs.indent();
        tgs.append("servPersistencia.anadirPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\", convertPrimitiveObjectsToString(");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
        tgs.append(".get");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(1));
        tgs.append("()));");
        tgs.newLine();
      }
    }

    for (SNode elem : SetSequence.fromSet(DomainObject__BehaviorDescriptor.getRelationships_id_n2UGGPVH.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi)))) {
      if ((boolean) DomainObjectComponent__BehaviorDescriptor.isCollection_id_n2UEXrwB.invoke(elem)) {
        tgs.indent();
        tgs.append("servPersistencia.eliminarPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\");");
        tgs.newLine();
        tgs.indent();
        tgs.append("servPersistencia.anadirPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\", convertDomainObjectsToString(");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
        tgs.append(".get");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(1));
        tgs.append("()));");
        tgs.newLine();
      } else {
        tgs.indent();
        tgs.append("servPersistencia.eliminarPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\");");
        tgs.newLine();
        tgs.indent();
        tgs.append("servPersistencia.anadirPropiedadEntidad(e");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
        tgs.append(", \"");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL));
        tgs.append("\", ");
        tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(0, 1).toLowerCase() + SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL).substring(1));
        tgs.append(".get");
        tgs.append(SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(elem, PROPS.name$MnvL).substring(1));
        tgs.append("());");
        tgs.newLine();
      }
    }

    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();



    tgs.indent();
    tgs.append("@Override");
    tgs.newLine();
    tgs.indent();
    tgs.append("public ");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" findById(");
    tgs.appendNode(DomainObject__BehaviorDescriptor.getPrimaryKeyType_id_n2UGq_9d.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi)));
    tgs.append(" id) {");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("Entidad e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(" = servPersistencia.recuperarEntidad(id);");
    tgs.newLine();
    tgs.indent();
    tgs.append("return entidadTo");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append("(e");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi), PROPS.name$MnvL));
    tgs.append(");");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    tgs.newLine();


    // If domain object associated with DAO has any attribute of type collection which stores primitive objects, then it is necessary to generate a private method that converts each of them into a string. This is because in the persistence service used each class property is stored as a string
    if (SetSequence.fromSet(DomainObject__BehaviorDescriptor.getAttributesCollectionType_id_n2UGP4CJ.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi))).isNotEmpty()) {
      tgs.indent();
      tgs.append("private String convertPrimitiveObjectsToString(Collection<Object> collection) {");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      tgs.append("StringBuilder string = new StringBuilder();");
      tgs.newLine();
      tgs.indent();
      tgs.append("collection.forEach(o -> string.append(o + \" \"));");
      tgs.newLine();
      tgs.indent();
      tgs.append("return string.toString().trim();");
      tgs.newLine();
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("}");
      tgs.newLine();
      tgs.newLine();
    }

    // If domain object associated with DAO has any relationship with cardinality 1..N or 0..N, then it is necessary to generate a private method that converts each of them into a string for the the same reason mentioned previously
    if (SetSequence.fromSet(DomainObject__BehaviorDescriptor.getRelationshipsManyCardinality_id_n2UGV4EI.invoke(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.domainObject$sOJi))).isNotEmpty()) {
      tgs.indent();
      tgs.append("private String convertDomainObjectsToString(Collection<Object> collection) {");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      tgs.append("StringBuilder string = new StringBuilder();");
      tgs.newLine();
      tgs.indent();
      tgs.append("collection.forEach(o -> string.append(o.getId() + \" \"));");
      tgs.newLine();
      tgs.indent();
      tgs.append("return string.toString().trim();");
      tgs.newLine();
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("}");
      tgs.newLine();
      tgs.newLine();
    }

    ctx.getBuffer().area().decreaseIndent();

    tgs.append("}");
    tgs.newLine();
    tgs.newLine();

  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Module$FI = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eab8a8900L, "CodeGenerationLanguaage.structure.Module");
    /*package*/ static final SConcept Integer$4L = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4afL, "CodeGenerationLanguaage.structure.Integer");
    /*package*/ static final SConcept Double$Z2 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edc6eL, "CodeGenerationLanguaage.structure.Double");
    /*package*/ static final SConcept Float$ob = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edc23L, "CodeGenerationLanguaage.structure.Float");
    /*package*/ static final SConcept Boolean$L2 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa4edcbbL, "CodeGenerationLanguaage.structure.Boolean");
    /*package*/ static final SConcept String$P8 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa28855bL, "CodeGenerationLanguaage.structure.String");
    /*package*/ static final SConcept CollectionType$L5 = MetaAdapterFactory.getConcept(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa2afa84L, "CodeGenerationLanguaage.structure.CollectionType");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink domainObject$sOJi = MetaAdapterFactory.getReferenceLink(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eac0f4b33L, 0x255c2eac906680L, "domainObject");
    /*package*/ static final SContainmentLink type$3xxQ = MetaAdapterFactory.getContainmentLink(0x46855889559641f7L, 0x9277402e4fbfedc8L, 0x255c2eaa12d4b8L, 0x255c2eaa12d4bbL, "type");
  }
}
